/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{vue,js,ts,jsx,tsx}",
  ],
  theme: {
    screens: {
      'sm': '640px',
      'md': '768px',
      'lg': '1024px',
      'xl': '1200px',
      '2xl': '1600px',
    },
    extend: {
      colors: {
        primary: '#2385FF',
        'primary-light': '#5AA7FF',
        'primary-dark': '#0D6EFD',
        'primary-bg': '#E8F3FF',
        danger: '#FF3B4A',
        'danger-bg': '#FFF0F0',
        orange: '#F59E0B',
        success: '#10B981',
        warning: '#FAAD14',
        'text-primary': '#333333',
        'text-secondary': '#707070',
        'text-aux': '#8C8C8C',
        border: '#F0F0F0',
        'bg-page': '#FFFFFF',
        'bg-nav': '#F5F5F5',
        'bg-card-hover': '#F5F5F5',
      },
      fontSize: {
        'h1-m': ['22px', { lineHeight: '1.35', fontWeight: '500' }],
        'h2-m': ['20px', { lineHeight: '1.35', fontWeight: '500' }],
        'h3-m': ['18px', { lineHeight: '1.35', fontWeight: '400' }],
        'body-m': ['16px', { lineHeight: '1.5', fontWeight: '400' }],
        'aux-m': ['14px', { lineHeight: '1.5', fontWeight: '400' }],
        'tiny-m': ['12px', { lineHeight: '1.4', fontWeight: '400' }],
        'h1': ['24px', { lineHeight: '1.35', fontWeight: '500' }],
        'h2': ['20px', { lineHeight: '1.35', fontWeight: '500' }],
        'h3': ['18px', { lineHeight: '1.35', fontWeight: '400' }],
        'body': ['16px', { lineHeight: '1.5', fontWeight: '400' }],
        'aux': ['14px', { lineHeight: '1.5', fontWeight: '400' }],
        'tiny': ['12px', { lineHeight: '1.4', fontWeight: '400' }],
      },
      spacing: {
        'xs': '4px',
        'sm': '8px',
        'md': '16px',
        'lg': '20px',
        'xl': '32px',
        '2xl': '48px',
        '3xl': '64px',
        '4xl': '80px',
      },
      borderRadius: {
        'sm': '4px',
        'md': '8px',
        'lg': '8px',
        'xl': '12px',
      },
      boxShadow: {
        'light': '0 1px 2px rgba(0, 0, 0, 0.04)',
        'medium': '0 4px 12px rgba(0, 0, 0, 0.08)',
        'heavy': '0 8px 24px rgba(0, 0, 0, 0.12)',
      },
      fontFamily: {
        sans: ['-apple-system', 'BlinkMacSystemFont', "'Segoe UI'", 'Roboto', "'Helvetica Neue'", 'Arial', 'sans-serif'],
      },
      width: {
        'sidebar': '240px',
        'sidebar-collapsed': '64px',
        'right-panel': '300px',
      },
    },
  },
  plugins: [],
}
